# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Klisuaiji (AI Figure Model Refiner)
# This file is part of the AI Figure Model Refiner (AFR) addon.
# AFR is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# AFR is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with AFR. If not, see <https://www.gnu.org/licenses/>.
"""Slicer CLI integration (V0.6/V0.7).

Detects common FDM slicer binaries and offers a thin wrapper that:
  - resolves the binary path,
  - generates a PrusaSlicer-compatible INI profile from our FDM
    settings (nozzle/layer/material/wall/density),
  - shells out to the slicer to produce G-code,
  - parses the resulting G-code for obvious problems (zero-length
    moves, retracted filament count, missing supports markers).

Pure stdlib + subprocess. We never bundle the slicer binaries
themselves — users install PrusaSlicer / OrcaSlicer / SuperSlicer
separately and we discover them on PATH or by well-known paths.
"""
import os
import re
import shutil
import subprocess
import sys
import tempfile


SLICER_BINARIES = (
    ("prusa-slicer", "PrusaSlicer"),
    ("PrusaSlicer", "PrusaSlicer"),
    ("prusa-slicer-console", "PrusaSlicer (console)"),
    ("orca-slicer", "OrcaSlicer"),
    ("OrcaSlicer", "OrcaSlicer"),
    ("superslicer", "SuperSlicer"),
    ("SuperSlicer", "SuperSlicer"),
    ("slic3r", "Slic3r"),
    ("cura", "Cura"),
)


def find_slicer():
    """Return (path, name) of the first slicer binary found on PATH.
    Returns (None, None) if none detected."""
    for binary, name in SLICER_BINARIES:
        p = shutil.which(binary)
        if p:
            return p, name
    return None, None


def find_all_slicers():
    """Return list of (path, name) for every slicer found on PATH."""
    found = []
    seen = set()
    for binary, name in SLICER_BINARIES:
        p = shutil.which(binary)
        if p and p not in seen:
            found.append((p, name))
            seen.add(p)
    return found


# ---------------------------------------------------------------------------
# INI profile generation
# ---------------------------------------------------------------------------
def _ini_bool(v):
    return "1" if v else "0"


def generate_ini_profile(settings, filepath=None, slicer="prusa"):
    """Write a Slic3r / PrusaSlicer INI profile based on our FDM
    settings. `settings` is a dict with keys:
      nozzle_mm, layer_height_mm, material (PLA/ABS/PETG),
      min_wall_thickness_mm, density_g_cm3.

    Returns the INI text (and writes to filepath if given).
    """
    nozzle = float(settings.get("nozzle_mm", 0.4))
    layer  = float(settings.get("layer_height_mm", 0.2))
    mat    = str(settings.get("material", "PLA")).upper()
    wall   = float(settings.get("min_wall_thickness_mm", 0.8))
    dens   = float(settings.get("density_g_cm3", 1.24))
    perimeter_count = max(2, int(round(wall / nozzle)))
    line_w = nozzle  # extruder default line width = nozzle
    sections = [
        ("print", [
            ("layer_height", "%.2f" % layer),
            ("first_layer_height", "%.2f" % max(layer, 0.2)),
            ("perimeters", str(perimeter_count)),
            ("top_solid_layers", "5"),
            ("bottom_solid_layers", "3"),
            ("fill_density", "20%"),
            ("perimeter_speed", "60"),
            ("infill_speed", "80"),
            ("support_material", "1"),
            ("support_material_threshold", "45"),
        ]),
        ("filament", [
            ("filament_type", mat),
            ("filament_density", "%.2f" % dens),
            ("filament_diameter", "1.75"),
            ("extrusion_multiplier", "1.0"),
        ]),
        ("printer", [
            ("nozzle_diameter", "%.2f" % nozzle),
            ("filament_diameter", "1.75"),
            ("bed_shape", "0x0,250x0,250x210,0x210"),
            ("max_print_speed", "150"),
        ]),
        ("extruder", [
            ("perimeter_extrusion_width", "%.2f" % line_w),
            ("infill_extrusion_width", "%.2f" % line_w),
            ("solid_infill_extrusion_width", "%.2f" % line_w),
            ("top_infill_extrusion_width", "%.2f" % line_w),
            ("support_material_extrusion_width", "%.2f" % line_w),
        ]),
    ]
    lines = ["# Generated by AI Figure Model Refiner (V0.6)"]
    for sec, kv in sections:
        lines.append("")
        lines.append("[%s]" % sec)
        for k, v in kv:
            lines.append("%s = %s" % (k, v))
    text = "\n".join(lines) + "\n"
    if filepath:
        os.makedirs(os.path.dirname(os.path.abspath(filepath)) or ".",
                    exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(text)
    return text


# ---------------------------------------------------------------------------
# Run a slicer
# ---------------------------------------------------------------------------
def slice_model(slicer_path, model_3mf_path, output_gcode=None,
                ini_profile=None, timeout=300, extra_args=None):
    """Invoke `slicer_path` to slice `model_3mf_path`. Returns dict with
    returncode, stdout, stderr, output_path."""
    if output_gcode is None:
        base = os.path.splitext(os.path.basename(model_3mf_path))[0]
        output_gcode = os.path.join(tempfile.gettempdir(),
                                    "afr_" + base + ".gcode")
    args = [slicer_path]
    # PrusaSlicer / SuperSlicer use --slice / --export-gcode
    args += ["--export-gcode", "--output", output_gcode]
    if ini_profile:
        args += ["--load", ini_profile]
    args += [model_3mf_path]
    if extra_args:
        args += list(extra_args)
    try:
        proc = subprocess.run(
            args, capture_output=True, text=True, timeout=timeout)
        return {
            "ok": proc.returncode == 0,
            "returncode": proc.returncode,
            "stdout": proc.stdout,
            "stderr": proc.stderr,
            "output_path": output_gcode if proc.returncode == 0 else None,
            "output_exists": os.path.isfile(output_gcode),
            "command": args,
        }
    except FileNotFoundError as e:
        return {"ok": False, "error": "slicer not found: %s" % e,
                "command": args}
    except subprocess.TimeoutExpired as e:
        return {"ok": False, "error": "slicer timed out after %ds" % timeout,
                "command": args}


# ---------------------------------------------------------------------------
# G-code verification (lightweight)
# ---------------------------------------------------------------------------
def verify_gcode(gcode_path, max_file_mb=200, sample_lines=100000):
    """Parse a G-code file and return basic sanity metrics.

    For files larger than max_file_mb we use **streaming sampling**:
    the first `sample_lines` and the last `sample_lines` lines are
    parsed, which gives a representative approximation without
    holding the whole file in memory.

    Heuristics:
      - counts G1 moves (print moves), G0 (travels)
      - counts retraction/de-retraction pairs (`G1 E-…` then `G1 E+…`)
      - counts support markers (PrusaSlicer / SuperSlicer emit
        "; support" or ";TYPE:Support" comments)
      - warns if no G1 found, file suspiciously small, or no support
        markers but model has overhangs (caller's responsibility to
        pass `expected_supports`).
    """
    out = {
        "path": gcode_path,
        "size_bytes": os.path.getsize(gcode_path)
                     if os.path.isfile(gcode_path) else 0,
        "g1_moves": 0,
        "g0_travels": 0,
        "retractions": 0,
        "unretractions": 0,
        "z_layer_changes": 0,
        "support_moves": 0,
        "max_lines": 0,
        "sampled": False,
        "issues": [],
    }
    if not os.path.isfile(gcode_path):
        out["issues"].append("file does not exist")
        return out
    streaming = out["size_bytes"] > max_file_mb * 1024 * 1024
    out["sampled"] = streaming
    last_z = None

    def _scan_line(line):
        nonlocal last_z
        out["max_lines"] += 1
        line = line.strip()
        if not line:
            return
        if line.startswith(";"):
            if "support" in line.lower() or ";type:support" in line.lower():
                out["support_moves"] += 1
            if "retract" in line.lower():
                out["retractions"] += 1
            return
        head = line.split(" ", 1)[0]
        if head == "G1" or head == "G0":
            if ";retract" in line.lower() or "; retract" in line.lower():
                out["retractions"] += 1
            m_e = re.search(r"E(-?\d+\.?\d*)", line)
            if m_e:
                e_val = float(m_e.group(1))
                if head == "G1":
                    if e_val < 0:
                        out["retractions"] += 1
                    elif e_val > 0 and out["retractions"] > out["unretractions"]:
                        out["unretractions"] += 1
            m_z = re.search(r"Z(-?\d+\.?\d*)", line)
            if m_z:
                z_val = float(m_z.group(1))
                if last_z is None or abs(z_val - last_z) > 1e-3:
                    out["z_layer_changes"] += 1
                    last_z = z_val
            if head == "G1":
                out["g1_moves"] += 1
            else:
                out["g0_travels"] += 1

    if not streaming:
        with open(gcode_path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                _scan_line(line)
    else:
        # head + tail sampling
        head_lines = []
        tail_lines = []
        with open(gcode_path, "r", encoding="utf-8", errors="ignore") as f:
            for i, line in enumerate(f):
                if i < sample_lines:
                    head_lines.append(line)
                else:
                    tail_lines.append(line)
                    if len(tail_lines) > sample_lines:
                        tail_lines.pop(0)
        for line in head_lines:
            _scan_line(line)
        for line in tail_lines:
            _scan_line(line)
    if out["g1_moves"] == 0:
        out["issues"].append("no G1 print moves found (empty/unsupported file?)")
    if out["retractions"] == 0:
        out["issues"].append("no retractions detected (stringing likely)")
    return out